version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mindspace-db:/usr/src/mysql

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: neo4j/test1234
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs

  backend:
    container_name: backend
    ##      mindspace_backend에서 확인할 때
    build: .
    ##     서브 모듈에서 확인할때 !docker-compose를 최상위 폴더로 빼야한다!
    #    build:
    #       context: ./Mindspace_backend
    #       Dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mindspace
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - neo4j

volumes:
  mindspace-db:
