profiles:
  default: local
spring:

  datasource:
    include:
#      - docker
      - local
#    url: jdbc:mysql://mysql:3306/mindspace?useUnicode=true&useSSL=false&createDatabaseIfNotExist=true&characterSetResults=UTF-8&characterEncoding=UTF-8&useLegacyDatetimeCode=false
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: password

  jpa:
    database: mysql
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: create